Some fixes
SicroAtGit/PureBasic-CodeArchiv-Rebirth pull request #13
Opened 2021-12-04 11:40 UTC by mk-soft-65

Update 28.11.2021
- Angepasst für ASM-Code
- Überprüfung und Korrektur Environment Variable "PB_TOOL_Compiler"
- PB Editor Standard Konstanten hinzugefügt
- Ausgabe in Standard Editor und Zwischenablage den asmCode ohne eigenen Header
- Include Dateien Abhängigkeiten aufgelöst

2021-12-04 11:47 UTC, mk-soft-65 commented
Sorry,

bad filename (Case)

2021-12-04 19:01 UTC, SicroAtGit commented
Thank you for the PR.

I saw [your post](https://www.purebasic.fr/german/viewtopic.php?p=361093#p361093) in the German PureBasic forum, but didn't have enough time to look at it in detail until now.

> * Check and correction of environment variable "PB_TOOL_Compiler"

I wonder if it doesn't make more sense if we wait until this [PB_TOOL_Compiler update delayed](https://www.purebasic.fr/english/viewtopic.php?t=72110) bug in the PureBasic IDE is fixed. Then we could rename this tool to _Display-ASM/C-Code_ or something like that and keep everything in one tool.

If I have enough time, I will have a look at the corresponding PureBasic IDE code and try to fix the bug.

> * PB Editor standard constants added

Thanks.

> * Output to standard editor and clipboard the asmCode without own header

We could add a checkbox gadget for this to make it optional (default is then all content, i.e. checkbox gadget is set). I think that some users want to take the whole content that is displayed in the textbox gadget.

> * Include files dependencies resolved

I prefer to keep dependencies external to avoid duplicate code and to only have to make improvements to the dependency code once in one place for each dependency.

2021-12-07 17:43 UTC, SicroAtGit commented
I have now created a [pull request with the `PB_TOOL_Compiler` fix](https://github.com/fantaisie-software/purebasic/pull/191) in the PureBasic IDE repository.

2022-02-06 11:25 UTC, SicroAtGit requested changes

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayASMcode.pb
> +; Update        : 28.11.2021
I don't like the author, author second and update lines and the minus character before word _Description_.

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayASMcode.pb
> +; Copyright (c) 2018-2020 Sicro
```suggestion
; Copyright (c) 2018-2020 Sicro
; Copyright (c) 2022 mk-soft
```

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayASMcode.pb
> +Procedure.i OpenWithStandardProgram(FilePath$)
Dependencies should not be inserted directly.

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayASMcode.pb
> +;XIncludeFile "../File/GetFileContentAsString.pbi"
Dependencies should not be inserted directly.

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayASMcode.pb
> +If file
Dependencies should not be inserted directly.

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +
I don't like the author, author second and update lines and the minus character before word _Description_.

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +; Copyright (c) 2018-2020 Sicro
```suggestion
; Copyright (c) 2018-2020 Sicro
; Copyright (c) 2022 mk-soft
```

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +Procedure.i OpenWithStandardProgram(FilePath$)
Dependencies should not be inserted directly.

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +;XIncludeFile "../File/GetFileContentAsString.pbi"
Dependencies should not be inserted directly.

2022-02-06 11:25 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +If file
Dependencies should not be inserted directly.

2022-02-06 11:31 UTC, SicroAtGit requested changes
Rename the code files:

- `displayASMcode.pb` => `DisplayASMCode.pb`
- `displayCcode.pb` => `DisplayCCode.pb`

2022-02-06 11:41 UTC, SicroAtGit commented
@mk-soft-65 I am still unsure if it should be two tools. Is it useful for you to have two separate tools?

2022-02-07 17:34 UTC, SicroAtGit requested changes

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/DisplayASMCode.pb
> +
I don't like this. Add a copyright line for you in the license instead:
```
; MIT License
;
; Copyright (c) 2018-2020 Sicro
; Copyright (c) 2021-2022 mk-soft
```

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/DisplayASMCode.pb
> +;XIncludeFile "../File/GetFileContentAsString.pbi"
Include file content should not be inserted. Please reset this change to the original code:
```
XIncludeFile "../System/OpenStandardProgram.pbi"
XIncludeFile "../File/GetFileContentAsString.pbi"
```

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/DisplayASMCode.pb
> +EndIf
Please reset this code to the original code:
```
asmCode$ = GetFileContentAsString(asmCodeFilePath$)
```

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +
I don't like this. Add a copyright line for you in the license instead:
```
; MIT License
;
; Copyright (c) 2018-2020 Sicro
; Copyright (c) 2022 mk-soft
```

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +;XIncludeFile "../File/GetFileContentAsString.pbi"
Include file content should not be inserted. Please reset this change to the original code:
```
XIncludeFile "../System/OpenStandardProgram.pbi"
XIncludeFile "../File/GetFileContentAsString.pbi"
```

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +Define asmCode$, output$, compilerOutput$
Please change:
- `asmCodeFilePath$` to `cCodeFilePath$`
- `asmCode$` to `asmCode$`

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +;-Create ASM Code File
Please replace `ASM` with `C`. There are more places in which this should be done, too.

2022-02-07 17:34 UTC, SicroAtGit commented on PB-IDE-Tools/displayCcode.pb
> +EndIf
Please reset this code to the original code:
```
cCode$ = GetFileContentAsString(cCodeFilePath$)
```

2022-02-13 12:36 UTC, SicroAtGit commented
I have now made the remaining changes and merged the commits into meaningful commits.

@mk-soft-65 Thanks a lot for your PR!

2022-02-13 12:38 UTC, merged